# Generated by Django 5.1.2 on 2024-10-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produtos',
            new_name='Produto',
        ),
    ]
